import img1 from "./images/haljina1.jpg";
import img2 from "./images/haljina2.jpg";
import img3 from "./images/haljina3.jpg";
import img4 from "./images/haljina4.jpg";
import img5 from "./images/haljina5.jpg";
import img6 from "./images/haljina6.jpg";
import img7 from "./images/haljina7.jpg";
import img8 from "./images/bluza1.jpg";
import img9 from "./images/bluza2.jpg";
import img10 from "./images/bluza3.jpg";
import img11 from "./images/bluza4.jpg";


import img12 from "./images/men1.jpg";
import img13 from "./images/men2.jpg";
import img14 from "./images/men3.jpg";
import img15 from "./images/men4.jpg";
import img16 from "./images/men5.jpg";
import img17 from "./images/men6.jpg";
import img18 from "./images/men7.jpg";
import img19 from "./images/men8.jpg";
import img20 from "./images/men9.jpg";


export default[
    {
        id:1,
        gender:"women",
        title:"dress rose",
        type:"clothes",
        designType:"dress",
        price:150,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img1,
        data:Date.now(),
    },
    {
        id:2,
        gender:"women",
        title:"dress mara",
        type:"clothes",
        designType:"dress",
        price:160,
        size:["M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img2,
        data:Date.now(),
    },
    {
        id:3,
        gender:"women",
        title:"dress anna",
        type:"clothes",
        designType:"dress",
        price:125,
        size:["S","M"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img3,
        data:Date.now(),
    },
    {
        id:4,
        gender:"women",
        title:"dress purple",
        type:"clothes",
        designType:"dress",
        price:145,
        size:["S","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img4,
        data:Date.now(),
    },
    {
        id:5,
        gender:"women",
        title:"dress sunsmile",
        type:"clothes",
        designType:"dress",
        price:110,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img5,
        data:Date.now(),
    },
    {
        id:6,
        gender:"women",
        title:"dress happiness",
        type:"clothes",
        designType:"dress",
        price:150,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img6,
        data:Date.now(),
    },
   
    {
        id:7,
        gender:"women",
        title:"My heart",
        type:"clothes",
        designType:"dress",
        price:120,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img7,
        data:Date.now(),
    },
  
    {
        id:8,
        gender:"women",
        title:"Little heart",
        type:"clothes",
        designType:"bluse",
        price:160,
        size:["S"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img8,
        data:Date.now(),
    },
    {
        id:9,
        gender:"women",
        title:"My sun",
        type:"clothes",
        designType:"bluse",
        price:120,
        size:["S","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img9,
        data:Date.now(),
    },
    {
        id:10,
        gender:"women",
        title:"lovely",
        type:"clothes",
        designType:"blue",
        price:150,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img10,
        data:Date.now(),
    },
    {
        id:11,
        gender:"women",
        title:"fire",
        type:"clothes",
        designType:"bluse",
        price:155,
        size:["S","M"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img11,
        data:Date.now(),
    },
    {
        id:12,
        gender:"men",
        title:"for man",
        type:"clothes",
        designType:"t-shirt",
        price:40,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img12,
        data:Date.now(),
    },
    {
        id:13,
        gender:"men",
        title:"perfecto",
        type:"clothes",
        designType:"t-shirt",
        price:55,
        size:["S","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img13,
        data:Date.now(),
    },
    {
        id:14,
        gender:"men",
        title:"for man",
        type:"clothes",
        designType:"t-shirt",
        price:40,
        size:["M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img14,
        data:Date.now(),
    },
    {
        id:15,
        gender:"men",
        title:"fire men",
        type:"clothes",
        designType:"t-shirt",
        price:40,
        size:["S","M"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img15,
        data:Date.now(),
    },
    {
        id:16,
        gender:"men",
        title:"for man",
        type:"clothes",
        designType:"t-shirt",
        price:45,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img16,
        data:Date.now(),
    },
    {
        id:17,
        gender:"men",
        title:"skinshirt",
        type:"clothes",
        designType:"shirt",
        price:40,
        size:["S","M"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img17,
        data:Date.now(),
    },
    {
        id:18,
        gender:"men",
        title:"for man",
        type:"clothes",
        designType:"shirt",
        price:30,
        size:["S","M","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img18,
        data:Date.now(),
    },
    {
        id:19,
        gender:"men",
        title:"for man",
        type:"clothes",
        designType:"shirt",
        price:45,
        size:["S","M"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img19,
        data:Date.now(),
    },
    {
        id:20,
        gender:"men",
        title:"for man",
        type:"clothes",
        designType:"shirt",
        price:55,
        size:["S","L"],
        descripton:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        cart:0,
        img:img20,
        data:Date.now(),
    },

  

]